services:
  - type: web
    name: phishguard
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
    # Auto-deploy on push
    autoDeploy: true
    # Health check path
    healthCheckPath: /
